// Generated by gencpp from file comm_bridge/GetAccResponse.msg
// DO NOT EDIT!


#ifndef COMM_BRIDGE_MESSAGE_GETACCRESPONSE_H
#define COMM_BRIDGE_MESSAGE_GETACCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comm_bridge
{
template <class ContainerAllocator>
struct GetAccResponse_
{
  typedef GetAccResponse_<ContainerAllocator> Type;

  GetAccResponse_()
    : respond()  {
    }
  GetAccResponse_(const ContainerAllocator& _alloc)
    : respond(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _respond_type;
  _respond_type respond;




  typedef boost::shared_ptr< ::comm_bridge::GetAccResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comm_bridge::GetAccResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetAccResponse_

typedef ::comm_bridge::GetAccResponse_<std::allocator<void> > GetAccResponse;

typedef boost::shared_ptr< ::comm_bridge::GetAccResponse > GetAccResponsePtr;
typedef boost::shared_ptr< ::comm_bridge::GetAccResponse const> GetAccResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comm_bridge::GetAccResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comm_bridge::GetAccResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comm_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comm_bridge::GetAccResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comm_bridge::GetAccResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comm_bridge::GetAccResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4556e909ee62344eea0a88d1ccb4917a";
  }

  static const char* value(const ::comm_bridge::GetAccResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4556e909ee62344eULL;
  static const uint64_t static_value2 = 0xea0a88d1ccb4917aULL;
};

template<class ContainerAllocator>
struct DataType< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comm_bridge/GetAccResponse";
  }

  static const char* value(const ::comm_bridge::GetAccResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] respond\n\
\n\
";
  }

  static const char* value(const ::comm_bridge::GetAccResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.respond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetAccResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comm_bridge::GetAccResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comm_bridge::GetAccResponse_<ContainerAllocator>& v)
  {
    s << indent << "respond[]" << std::endl;
    for (size_t i = 0; i < v.respond.size(); ++i)
    {
      s << indent << "  respond[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.respond[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMM_BRIDGE_MESSAGE_GETACCRESPONSE_H
