// Generated by gencpp from file comm_bridge/GetAcc.msg
// DO NOT EDIT!


#ifndef COMM_BRIDGE_MESSAGE_GETACC_H
#define COMM_BRIDGE_MESSAGE_GETACC_H

#include <ros/service_traits.h>


#include <comm_bridge/GetAccRequest.h>
#include <comm_bridge/GetAccResponse.h>


namespace comm_bridge
{

struct GetAcc
{

typedef GetAccRequest Request;
typedef GetAccResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAcc
} // namespace comm_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::comm_bridge::GetAcc > {
  static const char* value()
  {
    return "4556e909ee62344eea0a88d1ccb4917a";
  }

  static const char* value(const ::comm_bridge::GetAcc&) { return value(); }
};

template<>
struct DataType< ::comm_bridge::GetAcc > {
  static const char* value()
  {
    return "comm_bridge/GetAcc";
  }

  static const char* value(const ::comm_bridge::GetAcc&) { return value(); }
};


// service_traits::MD5Sum< ::comm_bridge::GetAccRequest> should match 
// service_traits::MD5Sum< ::comm_bridge::GetAcc > 
template<>
struct MD5Sum< ::comm_bridge::GetAccRequest>
{
  static const char* value()
  {
    return MD5Sum< ::comm_bridge::GetAcc >::value();
  }
  static const char* value(const ::comm_bridge::GetAccRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_bridge::GetAccRequest> should match 
// service_traits::DataType< ::comm_bridge::GetAcc > 
template<>
struct DataType< ::comm_bridge::GetAccRequest>
{
  static const char* value()
  {
    return DataType< ::comm_bridge::GetAcc >::value();
  }
  static const char* value(const ::comm_bridge::GetAccRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::comm_bridge::GetAccResponse> should match 
// service_traits::MD5Sum< ::comm_bridge::GetAcc > 
template<>
struct MD5Sum< ::comm_bridge::GetAccResponse>
{
  static const char* value()
  {
    return MD5Sum< ::comm_bridge::GetAcc >::value();
  }
  static const char* value(const ::comm_bridge::GetAccResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::comm_bridge::GetAccResponse> should match 
// service_traits::DataType< ::comm_bridge::GetAcc > 
template<>
struct DataType< ::comm_bridge::GetAccResponse>
{
  static const char* value()
  {
    return DataType< ::comm_bridge::GetAcc >::value();
  }
  static const char* value(const ::comm_bridge::GetAccResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COMM_BRIDGE_MESSAGE_GETACC_H
